### Health check
GET http://localhost:3000/health

### Get all shapes
GET http://localhost:3000/shapes

### Get specific shape
GET http://localhost:3000/shapes/10002005

### Get specific stop
GET http://localhost:3000/stops/1-100

### Get specific route
GET http://localhost:3000/routes/100001

### Get specific trip
GET http://localhost:3000/trips/347619649

### Get services operating on a specific date
GET http://localhost:3000/services/on/20251119